<a href="https://colab.research.google.com/github/juHa1205/NLP_2023/blob/main/1208.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
a = [[1,2,3],[4,5,6]]
b = np.array(a)
print(b)

[[1 2 3]
 [4 5 6]]


In [2]:
print(b.ndim)

2


In [3]:
print(b.shape)

(2, 3)


In [4]:
print(b[0,0])

1


In [5]:
print(np.arange(10))

[0 1 2 3 4 5 6 7 8 9]


In [6]:
print(np.arange(5,10))

[5 6 7 8 9]


In [9]:
print(np.zeros((2,2)))

[[0. 0.]
 [0. 0.]]


In [10]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
print(np.full((2,3),5))

[[5 5 5]
 [5 5 5]]


In [12]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
a = np.arange(20)

In [14]:
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [15]:
b=a.reshape((4,5))
print(b)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
