<a href="https://colab.research.google.com/github/juHa1205/NLP_2023/blob/main/numpy%EC%97%B0%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
a=[]#시프트+엔터 누르면 실행


In [2]:
type(a)

list

In [3]:
a=[0,1,2,3]

In [4]:
type(a)

list

In [5]:
b=['한남','전기전자']
type(b)

list

In [6]:
c=[0,1,2,'한남']
type(c)

list

In [7]:
a[0]

0

In [8]:
len(a)#통은 여러개 인데, 우리가 사용한 통은 지금 '리스트'임

4

In [9]:
import numpy as np #numpy를 불러오는데, 사용할 땐 np로 사용

# 파이썬에 다양한 모듈(라이브러리)가 있는데
#불러와서 사용하기 위한 방법

#코랩에서는 특별한 모듈을 제외하고 대부분 이미 설치되어 있음

# 불러와서 사용하면 됨

#틀별한 모듈을 사용하기 위해서는 : 설치 단계가 필요함

a = np.array([0,1,2,3])

In [10]:
print(np._version_) # 버젼 확인 (코랩네서 사용하는 버전)

AttributeError: ignored

In [11]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.full((3,3),True,dtype=bool) #크기:3x3,형식:bool

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [14]:
arr[arr%2==1]

array([-1, -1, -1, -1, -1])

In [ ]:
8%3

2

In [13]:
arr[arr%2==1]=-1

arr

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [ ]:
arr = np.arange(10)

In [ ]:
arr.shape# arr은 무슨 배열인지 알려준다. 현재 arr은 1차원 배열이다.
#reshape: shape 변경
#핵심은: 전체는 유지



(10,)

In [ ]:
b=arr.reshape(2,-1) #결과에 [[0,...],[5,...]] 나오는데 양끝에 대괄호는 반드시 있어야한다.
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
c=arr.reshape(2,5)
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
print(b.shape,c.shape)

(2, 5) (2, 5)


In [ ]:
d=arr.reshape(10,-1)
d

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [ ]:
a=np.arange(10).reshape(2,-1)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
b=np.repeat(1,10).reshape(2,-1)
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
f = np.concatenate([a,b],axis = 0)
 #핵심은 합치는 방향을 알려줘야함. 방향은 axis로 알려주기, axis = 0 이면 행 방향, axis = 1 이면 열방향
f

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [ ]:
e = np.concatenate([a,b],axis = 1)
e

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])